# Site
repository: HurryNair/HurryNair.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Harishankar S
title: SDE - HPE GMS Engineering
email: hari.nair634@gmail.com
website: https://hurrynair.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  HurryNair
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: __hari.nair__
linkedin_username: harishankar-s-203ab8136
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Codechef
  icon: fas fa-globe
  url: https://www.codechef.com/users/hari_nair
- title: YouTube
  icon: fab fa-youtube
  url: https://www.youtube.com/channel/UCBontgucOJVieImCi3cAx0Q

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Hari and I'm a software development engineer with a flair for datastructures & algorithms.

  I am most skilled in: <mark>Python</mark> <mark>Git</mark> <mark>REST</mark> <mark>Virtualization</mark> <mark>Containerization</mark> <mark>SQL</mark> <mark>Jenkins</mark> and <mark>Elastic</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Datacenter monitoring, reporting & dashboarding utility
        link: github.com/simplivity-prometheus-connector
        # link_text: Project Website
        additional_links:
          - title: HurryNair/simplivity-prometheus-connector
            icon: fab fa-github
            url: https://github.com/HurryNair/simplivity-prometheus-connector.git
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Observability and monitoring tool for an HCI based Simplivity datacenter
        description: | # this will include new lines to allow paragraphs
          Containerized hyperconverged infrastructure monitoring tool using Python, Docker, vmware, Prometheus, Grafana & REST APIs

      - layout: top-middle
        title: HPECP Python Library
        link: github.com/hpe-container-platform-community/hpecp-python-library
        # link_text: Project Website
        additional_links:
          - title: hpe-container-platform-community/hpecp-python-library
            icon: fab fa-github
            url: https://github.com/hpe-container-platform-community/hpecp-python-library
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Hewlett Packard Enterprise Container Platform library
        description: | # this will include new lines to allow paragraphs
          Python library and Command Line Interface (CLI) for creation, administration & management of HPE Container Platform (HPECP)
        
      - layout: top-middle
        title: ML classifier for Lighting fixture
        link: github.com/HurryNair/Lighting-fixture-classifier.git
        # link_text: Project Website
        additional_links:
          - title: HurryNair/Lighting-fixture-classifier
            icon: fab fa-github
            url: https://github.com/HurryNair/Lighting-fixture-classifier.git
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Lighting fixture classifier
        description: | # this will include new lines to allow paragraphs
          A transfer learning based image classifier for lighting fixtures

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hewlett Packard Enterprise
        link: https://www.hpe.com
        # link_text: hpe.com
        sub_title: Software Development Engineer
        caption: September 2021 - Present
        quote: >
          GMS Engineering
        description: | # this will include new lines to allow paragraphs
            Developing observability & monitoring utilities that enable proactive support and efficient administration of exabyte storage, compute and networking infrastructures for HPE GreenLake Managed Services

      - layout: left
        title: Hewlett Packard Enterprise
        link: https://www.hpe.com
        # link_text: hpe.com
        sub_title: Technical Solutions Consultant
        caption: January 2020 - August 2021
        quote: >
          SimpliVity CoE L2
        description: | # this will include new lines to allow paragraphs
            Administering virtualized environments & ensuring high availability for top contract accounts for a fortune 500 organization

      - layout: left
        title: Rousing Designs
        link: http://www.rousingdesigns.com/
        # link_text: rousingdesigns.com
        sub_title: Junior Python Developer
        caption: August 2019 - December 2019
        quote: >
          Software Development
        description: | # this will include new lines to allow paragraphs
            Worked on automating sales lead generation, data cleaning, databases & machine learning. 

      - layout: left
        title: Hewlett Packard Enterprise
        link: https://www.hpe.com
        # link_text: hpe.com
        sub_title: Storage Consultant Intern
        caption: January 2019 - May 2019
        quote: >
          Global Deployment Services
        description: | # this will include new lines to allow paragraphs
            Storage system analysis and design to improve effectiveness, reduce costs and apply scalability to meet business needs, while keeping user data safe.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Dayananda Sagar University
        caption: 2015 - 2019
        sub_title: Electronics & Communication Engineering
        quote: >
          CGPA 8.59
        description: | # this will include new lines to allow paragraphs
          - Published an IEEE paper on lighting automation & smart lighting
          - Built a pill dispenser that helps Old Age care homes automate pill distribution
          - Technovation 2018 winner
          - Literature club debate champion


      - layout: left
        title: St.Joseph's Pre-University College
        caption: 2013 - 2015
        sub_title: Electronics
        quote: >
          Annual score 84.9%
        description: | # this will include new lines to allow paragraphs
          - VP literature club

      - layout: left
        title: Presidency High School
        caption: 2001 - 2013
        sub_title: Schooling
        quote: >
          Annual score 88%
        description: | # this will include new lines to allow paragraphs
          - Five time annual rank holder
          - Cricket championship runner up 2009
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering I also have a blog
      - [O(1)](https://colab.research.google.com/drive/1KbqUKSwgLKOvu72JbVVNl7hv2JN_DZOy?usp=sharing)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
